"""delete lowercase name field for cluster model

Revision ID: 10ee7c1775d7
Revises: b02e400463df
Create Date: 2026-03-01 20:46:23.002601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ee7c1775d7'
down_revision: Union[str, Sequence[str], None] = 'b02e400463df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clusters_lowercase_name'), table_name='clusters')
    op.drop_column('clusters', 'lowercase_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('lowercase_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_clusters_lowercase_name'), 'clusters', ['lowercase_name'], unique=True)
    # ### end Alembic commands ###
