"""add pendind payments model

Revision ID: 28795494614f
Revises: 1bd3f115a76b
Create Date: 2026-02-21 14:51:53.166078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28795494614f'
down_revision: Union[str, Sequence[str], None] = '1bd3f115a76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_payments',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff_code', sa.String(length=64), nullable=False),
    sa.Column('is_extension', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=True),
    sa.Column('payment_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_pending_payments_telegram_id'), 'pending_payments', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_payments_telegram_id'), table_name='pending_payments')
    op.drop_table('pending_payments')
    # ### end Alembic commands ###
