"""update cluster model add peer model

Revision ID: b02e400463df
Revises: 2fa8eec7fc6e
Create Date: 2026-03-01 19:33:42.474406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02e400463df'
down_revision: Union[str, Sequence[str], None] = '2fa8eec7fc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peers',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peers_client_id'), 'peers', ['client_id'], unique=False)
    op.create_index(op.f('ix_peers_cluster_id'), 'peers', ['cluster_id'], unique=False)
    op.add_column('clusters', sa.Column('encrypted_password', sa.LargeBinary(), nullable=False))
    op.drop_column('clusters', 'iv')
    op.drop_column('clusters', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('password_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('iv', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('clusters', 'encrypted_password')
    op.drop_index(op.f('ix_peers_cluster_id'), table_name='peers')
    op.drop_index(op.f('ix_peers_client_id'), table_name='peers')
    op.drop_table('peers')
    # ### end Alembic commands ###
