"""updated peer anc cluster models

Revision ID: f5ea3bbf19b6
Revises: 6ac927a32a3a
Create Date: 2026-03-03 18:08:56.929943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ea3bbf19b6'
down_revision: Union[str, Sequence[str], None] = '6ac927a32a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('is_whitelist_gateway', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('clusters', sa.Column('region_code', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_clusters_is_whitelist_gateway'), 'clusters', ['is_whitelist_gateway'], unique=False)
    op.create_index(op.f('ix_clusters_region_code'), 'clusters', ['region_code'], unique=False)
    op.add_column('peers', sa.Column('key_type', sa.String(length=16), nullable=False, server_default='standard'))
    op.add_column('peers', sa.Column('region_code', sa.String(length=8), nullable=False, server_default=''))
    op.add_column('peers', sa.Column('client_email', sa.String(length=128), nullable=False, server_default=''))
    op.create_index(op.f('ix_peers_key_type'), 'peers', ['key_type'], unique=False)
    op.create_index(op.f('ix_peers_region_code'), 'peers', ['region_code'], unique=False)
    op.create_unique_constraint('uq_peer_client_cluster_type_region', 'peers', ['client_id', 'cluster_id', 'key_type', 'region_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_peer_client_cluster_type_region', 'peers', type_='unique')
    op.drop_index(op.f('ix_peers_region_code'), table_name='peers')
    op.drop_index(op.f('ix_peers_key_type'), table_name='peers')
    op.drop_column('peers', 'client_email')
    op.drop_column('peers', 'region_code')
    op.drop_column('peers', 'key_type')
    op.drop_index(op.f('ix_clusters_region_code'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_is_whitelist_gateway'), table_name='clusters')
    op.drop_column('clusters', 'region_code')
    op.drop_column('clusters', 'is_whitelist_gateway')
    # ### end Alembic commands ###
